name: push_notifications
description: PUSH NOTIFICATIONS
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.4.0
  flutter_native_timezone:
    path: C:/flutter_projects/OGtech/push_notifications/package/flutter_native_timezone-master
  provider: ^6.0.5
  timezone: ^0.8.0
  firebase_core: ^2.18.0
  firebase_messaging: ^14.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
